

$(function () {
	
	var u = $(".dear-joy");
	var f = $(".bp-line");
	var q = $(".bp-couplet-wrap");
	
	
	
	f.bind("bang", function () {
		var w = $(this).find(".bp-item");
		let count = 0;
		w.each(function (y, z) {
			setTimeout(function () {
				$(z).addClass("on hold-forwards bp-fly")
				if(++count == w.length){
				//	$("body").hide();
				}
			}, (w.length - y + 4) * 150)
		});

		
	});
	dearJoy()
	function dearJoy(){
		setTimeout(function(){
			let  d = $(".dear-joy");
			d.removeClass("jump").addClass("dian");
			setTimeout(function () {
				f.trigger("bang");
				d.removeClass("dian").addClass("jump");
			}, 500);

			$(".dear-joy2").addClass("fadeIn")
		},100)
		
	}

	$('#celebrateContainer').vfireworks({
		launchTime: 2000,
		clickLaunch: false,
		showRoute: false,
		fworkSpeed: 1,
		fworkAccel: 4,
		partCount: 165,
		partSpeed: 4,
		partSpeedVariance: 1,
		partFriction: 3,
		partGravity: 1,
		hueMin: 0,
		hueMax: 255,
		hueVariance: 255,
		lineWidth: 1,
		clearAlpha: 25
	});
})

var strVar = "";
var firecrackers = "";

firecrackers += "						<div class=\"bp-line line-shake\">\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay1 bg-ani-name2\" style=\"left:-22px; top:5px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(26deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay2 bg-ani-name1\" style=\"left:-2px; top:18.59076923076923px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-23deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay5 bg-ani-name2\" style=\"left:-22px; top:41.181538461538466px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(25deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay1 bg-ani-name1\" style=\"left:-2px; top:59.77230769230769px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-19deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>新<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay4 bg-ani-name1\" style=\"left:-22px; top:73.36307692307692px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(20deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name2\" style=\"left:-2px; top:84.95384615384616px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-27deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay4 bg-ani-name2\" style=\"left:-22px; top:99.54461538461538px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(26deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name2\" style=\"left:-2px; top:120.13538461538461px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay2 bg-ani-name1\" style=\"left:-22px; top:138.72615384615384px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(20deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay1 bg-ani-name2\" style=\"left:-2px; top:157.31692307692305px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-15deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay2 bg-ani-name2\" style=\"left:-22px; top:175.9076923076923px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(13deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay0 bg-ani-name1\" style=\"left:-2px; top:188.49846153846153px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-13deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay5 bg-ani-name2\" style=\"left:-22px; top:204.08923076923074px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(28deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay4 bg-ani-name2\" style=\"left:-2px; top:222.67999999999998px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-28deg);\">\n";
firecrackers += "										<div class=\"top\">\n";

firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay1 bg-ani-name2\" style=\"left:-22px; top:242.2707692307692px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(21deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay2 bg-ani-name1\" style=\"left:-2px; top:251.86153846153843px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-17deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay3 bg-ani-name1\" style=\"left:-22px; top:268.45230769230767px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(28deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name2\" style=\"left:-2px; top:284.0430769230769px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>新<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay5 bg-ani-name2\" style=\"left:-22px; top:304.6338461538461px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(12deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay2 bg-ani-name1\" style=\"left:-2px; top:316.22461538461533px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-19deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>新<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay1 bg-ani-name1\" style=\"left:-22px; top:336.8153846153846px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(19deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay1 bg-ani-name1\" style=\"left:-2px; top:349.4061538461538px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-25deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay0 bg-ani-name2\" style=\"left:-22px; top:372.99692307692305px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(27deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay4 bg-ani-name2\" style=\"left:-2px; top:382.5876923076923px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-26deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay3 bg-ani-name1\" style=\"left:-22px; top:407.1784615384615px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay2 bg-ani-name2\" style=\"left:-2px; top:416.7692307692307px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-16deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay4 bg-ani-name2\" style=\"left:-22px; top:431.35999999999996px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(19deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name2\" style=\"left:-2px; top:456.9507692307692px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-21deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay0 bg-ani-name2\" style=\"left:-22px; top:471.54153846153844px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(22deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>乐<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name2\" style=\"left:-2px; top:490.1323076923076px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-26deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay2 bg-ani-name2\" style=\"left:-22px; top:501.7230769230769px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(16deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay0 bg-ani-name2\" style=\"left:-2px; top:515.3138461538462px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-23deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay0 bg-ani-name1\" style=\"left:-22px; top:531.9046153846153px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(20deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay0 bg-ani-name1\" style=\"left:-2px; top:549.4953846153846px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>鼠<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay0 bg-ani-name2\" style=\"left:-22px; top:564.0861538461538px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang3\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay3 bg-ani-name1\" style=\"left:-2px; top:590.6769230769231px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay1 bg-ani-name1\" style=\"left:-22px; top:597.2676923076923px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(18deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay5 bg-ani-name1\" style=\"left:-2px; top:613.8584615384615px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-25deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>快<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay3 bg-ani-name1\" style=\"left:-22px; top:638.4492307692308px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(25deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang4\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-right bg-delay0 bg-ani-name1\" style=\"left:-2px; top:648.04px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(-21deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang1\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"bp-item bp-left bg-delay1 bg-ani-name2\" style=\"left:-22px; top:670.6307692307693px;\">\n";
firecrackers += "								<div class=\"bp-wrap\">\n";
firecrackers += "									<div class=\"bp\" style=\"transform: scale(0.8) rotate(13deg);\">\n";
firecrackers += "										<div class=\"top\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side up\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down1\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"side down2\">\n";
firecrackers += "											<i><\/i>\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"bottom foot\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "										<div class=\"text\">\n";
firecrackers += "											<div class=\"out\">\n";
firecrackers += "												<div class=\"mid\">\n";
firecrackers += "													<div class=\"in\">\n";
firecrackers += "													<\/div>\n";
firecrackers += "												<\/div>\n";
firecrackers += "											<\/div>\n";
firecrackers += "											<span>年<\/span>\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"bang bang2\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "						<\/div>\n";
firecrackers += "						<div class=\"scale0_7\">\n";
firecrackers += "							<div class=\"dear-joy jump\">\n";
firecrackers += "								<div class=\"joy-wrap\">\n";
firecrackers += "									";
firecrackers += "									";
firecrackers += "									<div class=\"left-ear\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"right-ear\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"left-hand\">\n";
firecrackers += "										<div class=\"sticks\">\n";
firecrackers += "										<\/div>\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"right-hand\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "									<div class=\"body\">\n";
firecrackers += "									<\/div>\n";
firecrackers += "								<\/div>\n";
firecrackers += "								<div class=\"shadow\">\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "							<div class=\"dear-joy2 hold-forwards\">\n";
firecrackers += "								<img class=\"\" src=\"images/laoshu.png\" alt=\"\">\n";
firecrackers += "								<div class=\"shadow\">\n";
firecrackers += "								<\/div>\n";
firecrackers += "							<\/div>\n";
firecrackers += "						<\/div>\n";
firecrackers += "						\n";
firecrackers += "					<\/div>\n";



strVar += "<div class=\"d-layout-area \">\n";
strVar += "	<div class=\"d-layout\" id=\"32315180\">\n";
strVar += "		<div class=\"d-layout-one d-w990 \">\n";
strVar += "				<div class=\"mc\" style=\" min-height:0px;\">\n";
strVar += "					<div id=\"rightBpBar\">\n";
strVar += firecrackers;
strVar += "					<div id=\"leftBpBar\">\n";
strVar += firecrackers;
strVar += "				<\/div>\n";
strVar += "			<\/div>\n";
strVar += "		<\/div>\n";
strVar += "	<\/div>\n";
strVar += "<\/div>\n";
$(".firecrackers").append(strVar)